### ISSUE TITLE
Write Bitrandom Drepreciation?

### ISSUE THREAD

**Issue by HaoZeke** [espressomd/espresso#711]
Hey, recently on the latest git build I ran into the following error while running the lj_tutorial file in the docs

sampling 9 at time=29.4 
unknown action "write bitrandom"
    while executing
"blockfile $cfile write bitrandom"
    (procedure "save_sim" line 11)
    invoked from within
"save_sim $blockfile "id pos v f q type" "all""
    ("for" body line 4)
    invoked from within
"for {set i 0} { $i < $sampling_iterations } { incr i} {
      incr nrep 
     integrate $sampling_interval
     save_sim $blockfile "id pos v f q type..."
    (file "lj_tutorial.tcl" line 195)

=======================================================
=                        lj_liquid_tutorial.tcl       =
=======================================================
 
Espresso Code Base : 
ESPResSo-3.4-dev-2417-g3304c50-git
{ Compilation status { DPD } { TABULATED } { COMFIXED } { LATTICE } { VIRTUAL_SITES_THERMOSTAT } { LJ_WARN_WHEN_CLOSE } { MORSE } { CONSTRAINTS } { ROTATIONAL_INERTIA } { FFTW } { EXCLUSIONS } { LJCOS2 } { LENNARD_JONES } { ROTATION } { VIRTUAL_SITES } { MPI_CORE } { NPT } { BOND_ANGLE } { LB } { ELECTROSTATICS } { SOFT_SPHERE } { MASS } { MODES } { P3M } { BOND_VIRTUAL } { EXTERNAL_FORCES } { PARTIAL_PERIODIC } { LENNARD_JONES_GENERIC } { MOLFORCES } { COMFORCE } { FORCE_CORE } { VIRTUAL_SITES_RELATIVE } { LJCOS } { BUCKINGHAM } }

Has this command been depreciated in favor of another?

**Comment by fweik** [comment]
I think this issue has been fixed. Can you try a current master?

**Comment by HaoZeke** [comment]
Nope, still not working..

=======================================================
=                        lj_liquid_tutorial.tcl       =
=======================================================
 
Espresso Code Base : 
ESPResSo-3.4-dev-2484-g6aa229c-dirty-git
{ Compilation status { EXTERNAL_FORCES } { P3M } { LENNARD_JONES } { ROTATIONAL_INERTIA } { LB } { VIRTUAL_SITES_RELATIVE } { MODES } { BOND_ANGLE } { MASS } { DPD } { LJCOS2 } { VIRTUAL_SITES } { MOLFORCES } { LJ_WARN_WHEN_CLOSE } { LJCOS } { EXCLUSIONS } { BOND_VIRTUAL } { ELECTROSTATICS } { TABULATED } { BUCKINGHAM } { COMFIXED } { MPI_CORE } { VIRTUAL_SITES_THERMOSTAT } { LATTICE } { CONSTRAINTS } { NPT } { COMFORCE } { PARTIAL_PERIODIC } { FORCE_CORE } { LENNARD_JONES_GENERIC } { MORSE } { SOFT_SPHERE } { FFTW } { ROTATION } }

 
 
 density = 0.8442 box_length = 5.2387886
Writing simlulation data to data/config.pdb
Start with minimal distance 0.13312517

Start warmup integration:
At maximum 2000 times 100 steps
Stop if minimal distance is larger than 0.87
run 67 at time=6.8 (LJ cap=68.0) min dist = 0.875215016
 Warm up finished 



sampling 9 at time=26.8 
unknown action "write bitrandom"
    while executing
"blockfile $cfile write bitrandom"
    (procedure "save_sim" line 11)
    invoked from within
"save_sim $blockfile "id pos v f q type" "all""
    ("for" body line 4)
    invoked from within
"for {set i 0} { $i < $sampling_iterations } { incr i} {
      incr nrep 
     integrate $sampling_interval
     save_sim $blockfile "id pos v f q type..."
    (file "lj_tutorial.tcl" line 195)

**Comment by fweik** [comment]
Ok I will look into this.
